import { height, padding, width } from "@mui/system";

export const employee_info = [
    {
        id: "fullName",
        x: 37,
        y: 160,
        width: 388,
        height: 17,
        size: 10,
        align: "center",
        verticalAlign: "middle",
    },
    {
        id: "address",
        x: 37,
        y: 221,
        width: 388,
        height: 30,
        size: 10,
        align: "left",
        verticalAlign: "top",
        padding: 3,
    },
    {
        id: "contactNumber",
        x: 90,
        y: 250,
        width: 336,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "email",
        x: 110,
        y: 264,
        width: 315,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "birthDate",
        x: 197,
        y: 295,
        width: 200,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "gender",
        genderPos: {
            male: { x: 144, y: 308 },
            female: { x: 231, y: 308 },
        },
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "civilStatus",
        civilStatusPos: {
            single: { x: 144, y: 327 },
            married: { x: 231, y: 326 },
            widowed: { x: 326, y: 328 },
        },
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "collegeSchool",
        x: 37,
        y: 397,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "collegeYearFrom",
        x: 218,
        y: 397,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "collegeYearTo",
        x: 303,
        y: 397,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "collegeDegree",
        x: 406,
        y: 397,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "seniorHighSchool",
        x: 37,
        y: 415,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "seniorHighYearFrom",
        x: 218,
        y: 415,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "seniorHighYearTo",
        x: 303,
        y: 415,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "seniorHighDegree",
        x: 406,
        y: 415,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "secondarySchool",
        x: 37,
        y: 434,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "secondaryYearFrom",
        x: 218,
        y: 434,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "secondaryYearTo",
        x: 303,
        y: 434,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "secondaryDegree",
        x: 406,
        y: 434,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "primarySchool",
        x: 37,
        y: 453,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "primaryYearFrom",
        x: 218,
        y: 453,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "primaryYearTo",
        x: 303,
        y: 453,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "primaryDegree",
        x: 406,
        y: 453,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workCompany1",
        x: 37,
        y: 500,
        width: 181,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPosition1",
        x: 218,
        y: 500,
        width: 188,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPeriod1",
        x: 406,
        y: 500,
        width: 176,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workCompany2",
        x: 37,
        y: 518,
        width: 181,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPosition2",
        x: 218,
        y: 518,
        width: 188,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPeriod2",
        x: 406,
        y: 518,
        width: 176,
        height: 17,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workCompany3",
        x: 37,
        y: 534,
        width: 181,
        height: 15,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPosition3",
        x: 218,
        y: 534,
        width: 188,
        height: 15,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workPeriod3",
        x: 406,
        y: 534,
        width: 176,
        height: 15,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "pwd",
        x: 186,
        y: 547,
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "iP",
        x: 237,
        y: 547,
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "victimOfArmedConflict",
        x: 277,
        y: 547,
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "rebelReturnee",
        x: 404,
        y: 547,
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "fourP",
        x: 255,
        y: 566,
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "othersDG",
        x: 336,
        y: 567,
        width: 246,
        height: 15,
        align: "bottom",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "emergencyName",
        x: 80,
        y: 707,
        width: 224,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "emergencyContact",
        x: 115,
        y: 723,
        width: 189,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "emergencyAddress",
        x: 85,
        y: 737,
        width: 218,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "gsisName",
        x: 390,
        y: 707,
        width: 192,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "gsisRelationship",
        x: 360,
        y: 723,
        width: 222,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "birthCertificate",
        x: 50,
        y: 855,
        size: 13,
    },
    {
        id: "transcriptOfRecords",
        x: 50,
        y: 870,
        size: 13,
    },
    {
        id: "barangayCertificate",
        x: 50,
        y: 886,
        size: 13,
    },
    {
        id: "form137138",
        x: 224,
        y: 855,
        size: 13,
    },
    {
        id: "diploma",
        x: 224,
        y: 870,
        size: 13,
    },
    {
        id: "othersD",
        x: 275,
        y: 886,
        width: 192,
        height: 13,
        align: "left",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "othersDCheck",
        x: 224,
        y: 886,
        size: 13,
    },
    {
        id: "certificationFromSchool",
        x: 433,
        y: 855,
        size: 13,
    },
];
