import { padding, width } from "@mui/system";

export const employee_info = [
    {
        id: "fullName",
        x: 37,
        y: 160,
        width: 388,
        height: 17,
        size: 10,
        align: "center",
        verticalAlign: "middle",
    },
    {
        id: "address",
        x: 37,
        y: 221,
        width: 388,
        height: 30,
        size: 10,
        align: "left",
        verticalAlign: "top",
        padding: 3,
    },
    {
        id: "contactNumber",
        x: 90,
        y: 250,
        width: 336,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "email",
        x: 110,
        y: 264,
        width: 315,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "birthDate",
        x: 197,
        y: 295,
        width: 200,
        height: 13,
        size: 10,
        align: "left",
        verticalAlign: "top",
    },
    {
        id: "gender",
        genderPos: {
            male: { x: 144, y: 308 },
            female: { x: 231, y: 308 },
        },
        align: "left",
        verticalAlign: "top",
        size: 13,
    },
    {
        id: "civilStatus",
        civilStatusPos: {
            single: { x: 144, y: 327 },
            married: { x: 231, y: 326 },
            widowed: { x: 326, y: 328 },
        },
        align: "left",
        verticalAlign: "top",
        size: 13
    },
    {
        id: "collegeSchool",
        x: 37,
        y: 397,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "collegeYearFrom",
        x: 218,
        y: 397,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "collegeYearTo",
        x: 303,
        y: 397,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "collegeDegree",
        x: 406,
        y: 397,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "seniorHighSchool",
        x: 37,
        y: 415,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "seniorHighYearFrom",
        x: 218,
        y: 415,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "seniorHighYearTo",
        x: 303,
        y: 415,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "seniorHighDegree",
        x: 406,
        y: 415,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "secondarySchool",
        x: 37,
        y: 434,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "secondaryYearFrom",
        x: 218,
        y: 434,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "secondaryYearTo",
        x: 303,
        y: 434,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "secondaryDegree",
        x: 406,
        y: 434,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "primarySchool",
        x: 37,
        y: 453,
        width: 181,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "primaryYearFrom",
        x: 218,
        y: 453,
        width: 85,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "primaryYearTo",
        x: 303,
        y: 453,
        width: 103,
        height: 18,
        align: "center",
        verticalAlign: "middle",
        size: 10,
    },
    {
        id: "primaryDegree",
        x: 406,
        y: 453,
        width: 176,
        height: 18,
        align: "left",
        verticalAlign: "middle",
        padding: 3,
        size: 10,
    },
    {
        id: "workCompany1",
        x: 40,
        y: 495,
        size: 8,
    },
    // {
    //     id: "workPosition",
    //     x: 220,
    //     y: 495,
    //     size: 8,
    // },
    // {
    //     id: "workPeriod",
    //     x: 409,
    //     y: 495,
    //     size: 8,
    // },
    // {
    //     id: "pwd",
    //     x: 186,
    //     y: 547,
    //     size: 8,
    // },
    // {
    //     id: "iP",
    //     x: 237,
    //     y: 547,
    //     size: 8,
    // },
    // {
    //     id: "victimOfArmedConflict",
    //     x: 277,
    //     y: 547,
    //     size: 8,
    // },
    // {
    //     id: "rebelReturnee",
    //     x: 404,
    //     y: 547,
    //     size: 8,
    // },
    // {
    //     id: "fourP",
    //     x: 255,
    //     y: 566,
    //     size: 8,
    // },
    // {
    //     id: "othersDG",
    //     x: 340,
    //     y: 564,
    //     size: 8,
    // },
    // {
    //     id: "emergencyName",
    //     x: 80,
    //     y: 705,
    //     size: 8,
    // },
    // {
    //     id: "emergencyContact",
    //     x: 115,
    //     y: 720,
    //     size: 8,
    // },
    // {
    //     id: "emergencyAddress",
    //     x: 85,
    //     y: 735,
    //     size: 8,
    // },
    // {
    //     id: "gsisName",
    //     x: 390,
    //     y: 704,
    //     size: 8,
    // },
    // {
    //     id: "gsisRelationship",
    //     x: 360,
    //     y: 720,
    //     size: 8,
    // },
    // {
    //     id: "birthCertificate",
    //     x: 50,
    //     y: 855,
    //     size: 8,
    // },
    // {
    //     id: "transcriptOfRecords",
    //     x: 50,
    //     y: 870,
    //     size: 8,
    // },
    // {
    //     id: "barangayCertificate",
    //     x: 50,
    //     y: 886,
    //     size: 8,
    // },
    // {
    //     id: "form137138",
    //     x: 224,
    //     y: 855,
    //     size: 8,
    // },
    // {
    //     id: "diploma",
    //     x: 224,
    //     y: 870,
    //     size: 8,
    // },
    // {
    //     id: "othersD",
    //     x: 224,
    //     y: 886,
    //     size: 8,
    // },
]