export const GIPApplicationFormFrames = [
    {
        fullName: {
            id: "fullName",
            x: 38,
            y: 160,
            width: 387,
            height: 28,
            type: "multiline",
            maxLines: 2,
            offset: 1,
            alignment: "left",
            autosize: true,
        },
        address: {
            id: "address",
            x: 38,
            y: height - 220,
            width: 387,
            height: 43,
            type: "multiline",
            maxLines: 2,
            offset: 1,
            alignment: "left",
            autosize: true,
        },
        landline: {
            id: "landline",
            x: 108,
            y: height - 235,
            width: 317,
            height: 13,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        phone: {
            id: "phone",
            x: 90,
            y: height - 250,
            width: 335,
            height: 13,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        email: {
            id: "email",
            x: 110,
            y: height - 265,
            width: 315,
            height: 13,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        birthPlace: {
            id: "birthPlace",
            x: 205,
            y: height - 280,
            width: 376,
            height: 13,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        birthDateMonth: {
            id: "birthDateMonth",
            x: 205,
            y: height - 296,
            width: 57,
            height: 15,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        birthDateDay: {
            id: "birthDateDay",
            x: 262,
            y: height - 296,
            width: 57,
            height: 15,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        birthDateYear: {
            id: "birthDateYear",
            x: 319,
            y: height - 296,
            width: 57,
            height: 15,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        genderM: {
            id: "genderM",
            x: 142,
            y: height - 311,
            width: 15,
            height: 14,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        genderF: {
            id: "genderF",
            x: 228,
            y: height - 309,
            width: 16,
            height: 13,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        civilStatusS: {
            id: "civilStatusS",
            x: 141,
            y: height - 329,
            width: 15,
            height: 14,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        civilStatusM: {
            id: "civilStatusM",
            x: 227,
            y: height - 328,
            width: 16,
            height: 14,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        civilStatusW: {
            id: "civilStatusW",
            x: 323,
            y: height - 329,
            width: 15,
            height: 14,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        collegeSchool: {
            id: "collegeSchool",
            x: 38,
            y: height - 396,
            width: 179,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        collegeYearFrom: {
            id: "collegeYearFrom",
            x: 219,
            y: height - 396,
            width: 83,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "center",
            autosize: true,
        },
        collegeYearTo: {
            id: "collegeYearTo",
            x: 305,
            y: height - 396,
            width: 100,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "center",
            autosize: true,
        },
        collegeDegree: {
            id: "collegeDegree",
            x: 407,
            y: height - 396,
            width: 174,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        seniorHighSchool: {
            id: "seniorHighSchool",
            x: 38,
            y: height - 415,
            width: 179,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "center",
            autosize: true,
        },
        seniorHighYearFrom: {
            id: "seniorHighYearFrom",
            x: 219,
            y: height - 415,
            width: 83,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "center",
            autosize: true,
        },
        seniorHighYearTo: {
            id: "seniorHighYearTo",
            x: 305,
            y: height - 415,
            width: 100,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "center",
            autosize: true,
        },
        seniorHighDegree: {
            id: "seniorHighDegree",
            x: 407,
            y: height - 415,
            width: 174,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        juniorHighSchool: {
            id: "juniorHighSchool",
            x: 38,
            y: height - 434,
            width: 179,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        juniorHighYearFrom: {
            id: "juniorHighYearFrom",
            x: 219,
            y: height - 434,
            width: 83,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        juniorHighYearTo: {
            id: "juniorHighYearTo",
            x: 305,
            y: height - 434,
            width: 100,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        juniorHighDegree: {
            id: "juniorHighDegree",
            x: 407,
            y: height - 434,
            width: 174,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        primarySchool: {
            id: "primarySchool",
            x: 38,
            y: height - 452,
            width: 179,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        primarySchoolYearFrom: {
            id: "primarySchoolYearFrom",
            x: 219,
            y: height - 452,
            width: 83,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        primarySchoolYearTo: {
            id: "primarySchoolYearTo",
            x: 305,
            y: height - 452,
            width: 100,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        primarySchoolDegree: {
            id: "primarySchoolDegree",
            x: 407,
            y: height - 452,
            width: 174,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        firstCompany: {
            id: "firstCompany",
            x: 38,
            y: height - 500,
            width: 180,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        firstCompanyPosition: {
            id: "firstCompanyPosition",
            x: 219,
            y: height - 500,
            width: 185,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
        firstCompanyPeriod: {
            id: "firstCompanyPeriod",
            x: 407,
            y: height - 500,
            width: 174,
            height: 17,
            type: "text",
            offset: 0,
            alignment: "left",
            autosize: true,
        },
    },
];
